version: "3.9"
services:
  api:
    build: .
    ports:
      - 3000:3000

  postgre:
    container_name: postgreports
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.3